import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { LeafletModule } from '@asymmetrik/ngx-leaflet';
import * as L from 'leaflet';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

@Component({
  standalone: true,
  selector: 'app-broker-dashboard',
  templateUrl: './broker-dashboard.component.html',
  styleUrls: ['./broker-dashboard.component.css'],
  imports: [CommonModule, FormsModule, LeafletModule]
})
export class BrokerDashboardComponent implements OnInit {
  isCollapsed = false;
  darkMode = false;
  brokerName = 'John Doe';

  stats = { total: 0, pending: 0, approved: 0, bound: 0 };
  searchTerm = '';
  sortKey: string = '';
  sortAsc: boolean = true;

  mapOptions: L.MapOptions = {
    center: L.latLng([20.5937, 78.9629]),
    zoom: 4
  };

  mapLayers: L.Layer[] = [
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18 }),
    L.marker([28.6139, 77.2090]).bindPopup('Delhi'),
    L.marker([19.0760, 72.8777]).bindPopup('Mumbai'),
    L.marker([13.0827, 80.2707]).bindPopup('Chennai')
  ];

  quotes = [
    { id: 'Q101', customer: 'Alice', premium: this.calculatePremium(1), status: 'Pending' },
    { id: 'Q102', customer: 'Bob', premium: this.calculatePremium(2), status: 'Approved' },
    { id: 'Q103', customer: 'Charlie', premium: this.calculatePremium(3), status: 'Bound' },
    { id: 'Q104', customer: 'Diana', premium: this.calculatePremium(4), status: 'Pending' }
  ];

  constructor() {}

  ngOnInit(): void {
    this.updateStats();
  }

  toggleSidebar() {
    this.isCollapsed = !this.isCollapsed;
  }

  toggleDarkMode() {
    this.darkMode = !this.darkMode;
    document.body.classList.toggle('dark-mode', this.darkMode);
  }

  calculatePremium(index: number): string {
    const base = 100;
    const rate = 20;
    return '$' + (base + rate * index);
  }

  updateStats(): void {
    this.stats.total = this.quotes.length;
    this.stats.pending = this.quotes.filter(q => q.status === 'Pending').length;
    this.stats.approved = this.quotes.filter(q => q.status === 'Approved').length;
    this.stats.bound = this.quotes.filter(q => q.status === 'Bound').length;
  }

  filteredQuotes() {
    let data = this.quotes.filter(q =>
      q.customer.toLowerCase().includes(this.searchTerm.toLowerCase())
    );

    if (this.sortKey) {
      data = data.sort((a, b) => {
        const aVal = (a as any)[this.sortKey];
        const bVal = (b as any)[this.sortKey];
        return this.sortAsc ? aVal.localeCompare(bVal) : bVal.localeCompare(aVal);
      });
    }

    return data;
  }

  sortBy(key: string) {
    if (this.sortKey === key) {
      this.sortAsc = !this.sortAsc;
    } else {
      this.sortKey = key;
      this.sortAsc = true;
    }
  }

  exportQuotesToPDF() {
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.text('MotoInsurance Quote Report', 14, 15);
    doc.setFontSize(11);
    doc.text(`Generated by: ${this.brokerName}`, 14, 23);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 30);

    const rows = this.filteredQuotes().map(q => [q.id, q.customer, q.premium, q.status]);

    autoTable(doc, {
      startY: 35,
      head: [['Quote ID', 'Customer', 'Premium', 'Status']],
      body: rows,
      styles: { halign: 'left' },
    });

    doc.save('filtered_quotes.pdf');
  }

  exportQuotesToCSV() {
    const headers = ['Quote ID', 'Customer', 'Premium', 'Status'];
    const rows = this.filteredQuotes().map(q => [q.id, q.customer, q.premium, q.status].join(','));
    const csvContent = 'data:text/csv;charset=utf-8,' + [headers.join(','), ...rows].join('\n');

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', 'filtered_quotes.csv');
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }

  viewQuote(quote: any) {
    alert(`Viewing Quote: ${JSON.stringify(quote, null, 2)}`);
  }

  editQuote(quote: any) {
    alert(`Editing Quote: ${JSON.stringify(quote, null, 2)}`);
  }

  deleteQuote(id: string) {
    const confirmDelete = confirm('Are you sure you want to delete this quote?');
    if (confirmDelete) {
      this.quotes = this.quotes.filter(q => q.id !== id);
      this.updateStats();
    }
  }

  createPolicy() {
    alert('Redirecting to create policy...');
  }

  viewAllPolicies() {
    alert('Showing all policies...');
  }

  viewExpiredPolicies() {
    alert('Listing expired policies...');
  }
}

